<a href="https://colab.research.google.com/github/Rohith-Rongali/EE5179-2023/blob/main/Tutorials/Tutorial-1/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
print(np.__version__)
import matplotlib.pylab as plt

1.22.4


# Numpy Basics:


**Exercise #1:** Creating a numpy array with particular value

**Your Task** Create a numpy array with size 2*3 with all elements as 5.

In [2]:
# YOUR CODE STARTS HERE
arr=np.zeros((2,3),dtype=int)+5
# YOUR CODE ENDS HERE
print(arr)

[[5 5 5]
 [5 5 5]]


**Exercise #2:** Creating a numpy array with *random* value

**Your Task** Create a numpy array with size 2*3 with all random values

In [3]:
# YOUR CODE STARTS HERE
rand_arr=np.random.randint(0,10,size=(2,3),dtype=int)
# YOUR CODE ENDS HERE
print(rand_arr)

[[0 6 3]
 [2 1 2]]


**Exercise #3:** Basic NumPy operatrions

**Your Task** For the random array `arr`defined above, find the `sum` of all the elements, `mean`, `maximum` and `minimum` value

In [4]:
#YOUR CODE STARTS HERE
arr_sum = rand_arr.sum()
arr_mean = rand_arr.mean()
arr_max = rand_arr.max()
arr_min = rand_arr.min()
#YOUR CODE ENDS HERE

print(f'sum: {arr_sum}\nmean: {arr_mean}\nmax: {arr_max}\nmin:{arr_min}')

sum: 14
mean: 2.3333333333333335
max: 6
min:0


**Exercise #4:** `argmin` and `argmax`

**Your Task** For the random array `arr`defined below:

*   Find the position of maximum and minimum value of above array
*   Find the indices of maximum and minimum value along each of its columns.
*   Find the indices of maximum and minimum value along each of the its rows.



In [3]:
# Define an array
arr = np.array([[5,12,51,25] ,[25,29,2,27]])
print(f'Array:\n{arr}\n')
# YOUR CODE STARTS HERE
#Find the position of maximum and minimum value of above array
print(f'Indices for Maximum : {arr.argmax()} and Indices for Minimum : {arr.argmin()}')
#Find the indices of maximum and minimum value along each of its columns.
print(f'Indices for Maximum : {arr.argmax(axis=0)} and Indices for Minimum : {arr.argmin(axis=0)}')
#Find the indices of maximum and minimum value along each of the its rows.
print(f'Indices for Maximum : {arr.argmax(axis=1)} and Indices for Minimum : {arr.argmin(axis=1)}')
#YOUR CODE ENDS HERE

Array:
[[ 5 12 51 25]
 [25 29  2 27]]

Indices for Maximum : 2 and Indices for Minimum : 6
Indices for Maximum : [1 1 0 1] and Indices for Minimum : [0 0 1 0]
Indices for Maximum : [2 1] and Indices for Minimum : [0 2]


Numpy Arrays vs. Python Lists?

    Why the need for numpy arrays? Can't we just use Python lists?
    Iterating over numpy arrays is slow. Slicing is faster

Python lists may contain items of different types. This flexibility comes at a price: Python lists store pointers to memory locations. On the other hand, numpy arrays are typed, where the default type is floating point. Because of this, the system knows how much memory to allocate, and if you ask for an array of size 100, it will allocate one hundred contiguous spots in memory, where the size of each spot is based on the type. This makes access extremely fast.


If you want to know more, we will suggest that you read this from [Jake Vanderplas's Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/). You will find that book an incredible resource for learning numpy, pandas and plotting. All the lessons are available as colab notebooks so that u can try out the commands on your own.